version: '3.9'
services:
  db:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_USER: kenet
      POSTGRES_PASSWORD: 3322
      POSTGRES_DB: crudreactexpress
    ports:
      - "4000:5432"
    volumes:
      - db_kenet_33:/var/lib/postgresql/data

volumes:
  db_kenet_33:
